version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017

  agency-backend:
    image: agency-backend:1.1
    container_name: agency-backend
    ports:
      - 8081:8080
    links:
      - mongodb
    restart: on-failure
    depends_on:
      - mongodb